# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5da38fde4cada84055e4ea4ee59fa05e5c81804a78b879de4a5435468842a491f9b3e3a16ee7429026782413874b0338a147fe1167660d21e561f7aac5c64cb6

test:
  secret_key_base: e67ad80527de1e2625a6a5eeffadb98002b74a358b880001aae288e04f87cce806faa8b210803d8fff398d71463f391d7041536c6a3c283ef3f62376b974343b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
